PlusOneHub:
  members:
    arun02139: U2KDQKL5D
    MaximHordijchuk: U92AW9U4E
    sschoellhammer: U9P65RDRS
    Prorokus: U275VJTFX
    wowzhoe: U7T525XPE
    oniboxblink: U6V82EC4V
    haopengy: U499B2Z0C
    nadiialitslink: U9BHL7799
    mariakysliakova: U74SHNL85
    addisondebolt: U7FKLA1EU
    heliosphereman: U43BXGHRR
    dyoxyne: UD9B3AUDP
    alexLitslink: UAGKTKL07
    nbrindic: UAVMCN62D
    PlusOne-Alex: UC876SE8H

  channel:
    "#pull-requests"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.
    - Try to pair when possible.
    - Be considerate to remote workers and follow the Working from home practices https://gov-uk.atlassian.net/wiki/x/Bz_5Bw and https://gov-uk.atlassian.net/wiki/display/CT/Working+from+home+ideas
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Set your Slack status to away or do not disturb so people know whether they can disturb you.
    - Has your story got points?
    - Don't forget to assign your face to a card and PR if you're working on it or reviewing.
    - Don't forget the Jabra and fisheye lens if you're dialing in people!
    - If Hangouts is being flaky, try Slack calls or appear.in!
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:
